=== PowerNukkit/PowerNukkit-Universal-Converters/api/src/main/resources/org/powernukkit/converters/platform/universal/definitions/universal-blocks.dtd
<!--
  -  PowerNukkit Universal Worlds & Converters for Minecraft
  -  Copyright (C) 2021  José Roberto de Araújo Júnior
  -
  -  This program is free software: you can redistribute it and/or modify
  -  it under the terms of the GNU Affero General Public License as published by
  -  the Free Software Foundation, either version 3 of the License, or
  -  (at your option) any later version.
  -
  -  This program is distributed in the hope that it will be useful,
  -  but WITHOUT ANY WARRANTY; without even the implied warranty of
  -  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  -  GNU Affero General Public License for more details.
  -
  - You should have received a copy of the GNU Affero General Public License
  - along with this program.  If not, see <https://www.gnu.org/licenses/>.
  -->

<!ELEMENT int-range EMPTY>
<!ATTLIST int-range
        from         CDATA   "0"
        to           CDATA   #REQUIRED>

<!ELEMENT value (#PCDATA)>
<!ATTLIST value
        default (true|false)  "false"
        java    NMTOKEN     #IMPLIED
        bedrock NMTOKEN     #IMPLIED>

<!ELEMENT copy-values EMPTY>
<!ATTLIST copy-values   from  IDREF   #REQUIRED>

<!ELEMENT boolean EMPTY>
<!ATTLIST boolean
        default    (true|false)   "false"
        java-false    NMTOKEN     'false'
        bedrock-false NMTOKEN     '0'
        java-true     NMTOKEN     'true'
        bedrock-true  NMTOKEN     '1'>

<!ELEMENT block-property (int-range|boolean|(value|copy-values)+)>
<!ATTLIST block-property
        id      ID          #REQUIRED
        java    NMTOKEN     #IMPLIED
        bedrock NMTOKEN     #IMPLIED
        java-requires-adapter       (true|false) "false"
        bedrock-requires-adapter    (true|false) "false">

<!ELEMENT block-properties (block-property+)>

<!ELEMENT uses-property EMPTY>
<!ATTLIST uses-property 
        named   IDREF   #REQUIRED
        on-universal (true|false|optional) "true"
        on-java (true|false) "true"
        on-bedrock (true|false) "true">

<!ELEMENT uses-block-entity EMPTY>
<!ATTLIST uses-block-entity
        named IDREF #REQUIRED
        on-universal (true|false|optional) "true"
        on-java (true|false) "true"
        on-bedrock (true|false) "true">

<!ELEMENT extra-block (uses-property*)>
<!ATTLIST extra-block
        on (java|bedrock|both) #REQUIRED
        id  NMTOKEN            #REQUIRED
        inherit-properties  (true|false)    "true">

<!ELEMENT block-type (uses-property*,uses-block-entity?,extra-block*)>
<!ATTLIST block-type
        id      ID          #REQUIRED
        java    NMTOKEN     #IMPLIED
        bedrock NMTOKEN     #IMPLIED
        java-requires-adapter       (true|false) "false"
        bedrock-requires-adapter    (true|false) "false">

<!ELEMENT block-types (block-type+)>

<!ELEMENT data EMPTY>
<!ATTLIST data
        name    NMTOKEN     #REQUIRED
        type    (int|long|string|text|boolean|block_id|status_effect_id|item_stack|dye_color|item_list|loot_table|findable|int_coordinate|beehive_occupants|banner_patterns|int_list|none)  #REQUIRED
        optional    (true|false)    "false"
        default     CDATA       #IMPLIED
        java-name    NMTOKEN     #IMPLIED
        bedrock-name NMTOKEN     #IMPLIED
        java-optional    (true|false)    #IMPLIED
        bedrock-optional    (true|false)    #IMPLIED
        
        java-type (none|byte|short|int|long|boolean|float|double|string|item_stack|json_text|int_list) #IMPLIED
        bedrock-type (none|byte|short|int|long|boolean|float|double|string|item_stack|i18n_text) #IMPLIED
        java-requires-adapter       (true|false) "false"
        bedrock-requires-adapter    (true|false) "false">

<!ELEMENT block-entity (data*)>
<!ATTLIST block-entity
        id      ID          #REQUIRED
        java    NMTOKEN     #REQUIRED
        bedrock NMTOKEN     #REQUIRED>

<!ELEMENT block-entities (block-entity+)>

<!ELEMENT universal-blocks (block-properties,block-entities,block-types)>

=== PowerNukkit/PowerNukkit-Universal-Converters/api/src/main/resources/org/powernukkit/converters/platform/universal/definitions/universal-blocks.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  ~  PowerNukkit Universal Worlds & Converters for Minecraft
  ~  Copyright (C) 2021  José Roberto de Araújo Júnior
  ~
  ~  This program is free software: you can redistribute it and/or modify
  ~  it under the terms of the GNU Affero General Public License as published by
  ~  the Free Software Foundation, either version 3 of the License, or
  ~  (at your option) any later version.
  ~
  ~  This program is distributed in the hope that it will be useful,
  ~  but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~  GNU Affero General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program.  If not, see <https://www.gnu.org/licenses/>.
  -->

<!DOCTYPE universal-blocks SYSTEM "universal-blocks.dtd">
<universal-blocks>
    <block-properties>
        <block-property id="sapling_age" java="stage" bedrock="age_bit">
            <boolean java-false="0" java-true="1"/>
        </block-property>
        <block-property id="allow_underwater" bedrock="allow_underwater_bit" java-requires-adapter="true">
            <boolean/>
        </block-property>
        <block-property id="attached" bedrock="attached_bit">
            <boolean/>
        </block-property>
        <block-property id="attachment">
            <value java="floor" default="true">standing</value>
            <value java="ceiling">hanging</value>
            <value java="single_wall">side</value>
            <value java="double_wall">multiple</value>
        </block-property>
        <block-property id="bamboo_leaves" bedrock="bamboo_leaf_size" java="leaves">
            <value bedrock="no_leaves" default="true">none</value>
            <value bedrock="small_leaves">small</value>
            <value bedrock="large_leaves">large</value>
        </block-property>
        <block-property id="bamboo_stalk_thickness" java="stage">
            <value java="0">thin</value>
            <value java="1">thick</value>
        </block-property>
        <block-property id="bites" bedrock="bite_counter">
            <int-range to="6"/>
        </block-property>
        <block-property id="block_light_level" java-requires-adapter="true">
            <int-range to="15"/>
        </block-property>
        <block-property id="brewing_stand_slot_a" bedrock="brewing_stand_slot_a_bit" java="has_bottle_0">
            <boolean/>
        </block-property>
        <block-property id="brewing_stand_slot_b" bedrock="brewing_stand_slot_b_bit" java="has_bottle_1">
            <boolean/>
        </block-property>
        <block-property id="brewing_stand_slot_c" bedrock="brewing_stand_slot_c_bit" java="has_bottle_2">
            <boolean/>
        </block-property>
        <block-property id="powered" bedrock="powered_bit">
            <boolean/>
        </block-property>
        <block-property id="button_pressed" bedrock="button_pressed_bit">
            <boolean/>
        </block-property>
        <block-property id="face" bedrock-requires-adapter="true">
            <value>celling</value>
            <value>floor</value>
            <value>wall</value>
        </block-property>
        <block-property id="horizontal_direction" bedrock="direction" java="facing">
            <value bedrock="0" default="true">south</value>
            <value bedrock="1">west</value>
            <value bedrock="2">north</value>
            <value bedrock="3">east</value>
        </block-property>
        <block-property id="stairs_direction" bedrock="weirdo_direction" java="facing">
            <value bedrock="0" default="true">east</value>
            <value bedrock="1">west</value>
            <value bedrock="2">south</value>
            <value bedrock="3">north</value>
        </block-property>
        <block-property id="trapdoor_direction" bedrock="direction" java="facing">
            <copy-values from="stairs_direction"/>
        </block-property>
        <block-property id="chest_type" bedrock-requires-adapter="true">
            <value>left</value>
            <value>right</value>
            <value>single</value>
        </block-property>
        <block-property id="chest_direction" java="facing" bedrock="facing_direction">
            <value bedrock="2" default="true">north</value>
            <value bedrock="3">south</value>
            <value bedrock="4">west</value>
            <value bedrock="5">east</value>
        </block-property>
        <block-property id="facing_direction" java="facing">
            <value bedrock="0" default="true">down</value>
            <value bedrock="1">up</value>
            <value bedrock="2">north</value>
            <value bedrock="3">south</value>
            <value bedrock="4">west</value>
            <value bedrock="5">east</value>
        </block-property>
        <block-property id="hopper_direction" java="facing">
            <value bedrock="0" default="true">down</value>
            <value bedrock="2">north</value>
            <value bedrock="3">south</value>
            <value bedrock="4">west</value>
            <value bedrock="5">east</value>
        </block-property>
        <block-property id="door_direction" bedrock="direction" java="facing">
            <value bedrock="0" default="true">east</value>
            <value bedrock="1">south</value>
            <value bedrock="2">west</value>
            <value bedrock="3">north</value>
        </block-property>
        <block-property id="anvil_direction" java="facing" bedrock="direction">
            <value bedrock="0" default="true">north</value>
            <value bedrock="1">east</value>
            <value bedrock="2">south</value>
            <value bedrock="3">west</value>
        </block-property>
        <block-property id="observer_direction" bedrock="facing_direction" java="facing">
            <value bedrock="0" default="true">south</value>
            <value bedrock="1">up</value>
            <value bedrock="2">north</value>
            <value bedrock="3">down</value>
            <value bedrock="4">west</value>
            <value bedrock="5">east</value>
        </block-property>
        <block-property id="bed_direction" bedrock="facing_bit" java="facing">
            <value bedrock="0" default="true">north</value>
            <value bedrock="1">west</value>
            <value bedrock="2">south</value>
            <value bedrock="3">east</value>
        </block-property>
        <block-property id="tall_block_half" bedrock="upper_block_bit" java="half">
            <boolean java-false="lower" java-true="upper"/>
        </block-property>
        <block-property id="door_hinge" bedrock="door_hinge_bit" java="hinge">
            <value bedrock="0">left</value>
            <value bedrock="1">right</value>
        </block-property>
        <block-property id="cauldron_liquid" java-requires-adapter="true">
            <value>water</value>
            <value>lava</value>
        </block-property>
        <block-property id="open" bedrock="open_bit">
            <boolean/>
        </block-property>
        <block-property id="chemistry_table_type" java-requires-adapter="true">
            <value>compound_creator</value>
            <value>material_reducer</value>
            <value>element_constructor</value>
            <value>lab_table</value>
        </block-property>
        <block-property id="burnable_wood" bedrock="wood_type" java-requires-adapter="true">
            <value>acacia</value>
            <value>birch</value>
            <value>dark_oak</value>
            <value>jungle</value>
            <value>oak</value>
            <value>spruce</value>
        </block-property>
        <block-property id="fireproof_wood" java-requires-adapter="true" bedrock-requires-adapter="true">
            <value>crimson</value>
            <value>warped</value>
        </block-property>
        <block-property id="wood_type" java-requires-adapter="true" bedrock-requires-adapter="true">
            <copy-values from="burnable_wood" />
            <copy-values from="fireproof_wood" />
        </block-property>
        <block-property id="smooth_stone_type" java-requires-adapter="true" bedrock-requires-adapter="true">
            <value>stone</value>
            <value>polished_blackstone</value>
        </block-property>
        <block-property id="wood_or_stone_type" java-requires-adapter="true" bedrock-requires-adapter="true">
            <copy-values from="wood_type"/>
            <copy-values from="smooth_stone_type"/>
        </block-property>
        <block-property id="door_type" java-requires-adapter="true" bedrock-requires-adapter="true">
            <copy-values from="wood_type"/>
            <value>iron</value>
        </block-property>
        <block-property id="fence_type" java-requires-adapter="true" bedrock-requires-adapter="true">
            <copy-values from="wood_type"/>
            <value>nether_brick</value>
        </block-property>
        <block-property id="chemical_element" java-requires-adapter="true">
            <int-range to="118"/>
        </block-property>
        <block-property id="in_wall" bedrock="in_wall_bit">
            <boolean/>
        </block-property>
        <block-property id="waterlogged" bedrock-requires-adapter="true">
            <boolean/>
        </block-property>
        <block-property id="connect_east" bedrock-requires-adapter="true" java="east">
            <boolean/>
        </block-property>
        <block-property id="connect_west" bedrock-requires-adapter="true" java="west">
            <boolean/>
        </block-property>
        <block-property id="connect_south" bedrock-requires-adapter="true" java="south">
            <boolean/>
        </block-property>
        <block-property id="connect_north" bedrock-requires-adapter="true" java="north">
            <boolean/>
        </block-property>
